default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  host: localhost
  port: 5432
  username: postgres
  password: nguyen

development:
  <<: *default
  database: rails_5_starter_development

test:
  <<: *default
  database: rails_5_starter_test

production:
  <<: *default
  database: rails_5_starter_production
  username: rails_5_starter
  password: <%= ENV['RAILS_5_STARTER_DATABASE_PASSWORD'] %>
